write_poem:
  description: >
    Generate a funny, light hearted poem about how life, love, universe and everything 
    is awesome 
    Ensure the poem is engaging and adheres to the specified sentence count of {sentence_count}.
  expected_output: >
    A beautifully crafted poem about CrewAI, with exactly {sentence_count} sentences.
  agent: poem_writer
