research_task:
  description: >
    Conduct focused research on "{query}" with these key objectives:
    1. Gather accurate information about the technology/product (current year: {current_year})
    2. Identify the main features and capabilities
    3. Explore common use cases and applications
    4. Note key strengths and potential limitations
    5. Find examples of real-world implementations where available
    6. Consider how it compares to similar technologies
    
    Guidelines:
    - Focus on quality information rather than quantity
    - Prioritize accuracy and relevance over exhaustiveness
    - Include 5-10 key points with supporting details
    - Cite sources when possible using a simple format: [Source Name]
    - Organize findings in a clear, easy-to-read format
    - Keep technical details balanced with practical information
  expected_output: >
    A clear, structured research document with:
    - 5-10 well-researched key points organized in logical sections
    - Each point supported by relevant details and examples
    - Basic citations for important information
    - Balanced coverage of benefits and limitations
    - Simple comparisons with alternatives when relevant
    - Brief conclusion summarizing the findings
  agent: researcher

reporting_task:
  description: >
    Create a clean HTML report based on the research findings. Your report should:
    1. Begin with a brief summary that includes the original question: "{query}"
    2. Organize information into clear sections with appropriate headings
    3. Include key points and examples from the research
    4. Highlight both benefits and limitations
    5. Add a concise conclusion with basic recommendations
    6. Format the document professionally with clean styling
    7. Use occasional emojis to highlight important points
    8. Include proper UTF-8 encoding declaration for character support
    9. Add a simple references section if sources were cited
    
    Guidelines:
    - Create a focused report that presents the key information clearly
    - Use tables, lists, and formatting to improve readability
    - Balance technical details with practical insights
    - Aim for quality over quantity in both content and visual elements
    - Keep the design clean and professional
  expected_output: >
    A clean, professional HTML report that includes:
    - Proper HTML5 doctype and UTF-8 charset declaration
    - Simple, readable HTML with basic CSS styling
    - Title with current date
    - Brief summary with the original question clearly stated
    - Content organized in logical sections with clear headings
    - Key points from the research with supporting details
    - Simple tables or lists for comparing features when relevant
    - Strategic use of emojis to highlight important points
    - Basic citations for sources when provided
    - Footer with generation date
    - Clean, consistent styling throughout the document
  agent: reporting_analyst
  output_file: output/answer.html
